# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('min_value', models.DecimalField(decimal_places=1, max_digits=16)),
                ('max_value', models.DecimalField(decimal_places=1, max_digits=16)),
                ('min_color', models.CharField(blank=True, max_length=7, null=True)),
                ('max_color', models.CharField(blank=True, max_length=7, null=True)),
                ('intervals', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('filepath', models.FileField(blank=True, max_length=255, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='column',
            name='data_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_file.DataFile'),
        ),
    ]
