# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_file', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='filepath',
        ),
        migrations.AddField(
            model_name='datafile',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='/tmp'),
        ),
    ]
