# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_file', '0002_auto_20170308_2148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datafile',
            options={'get_latest_by': 'time_created'},
        ),
        migrations.AddField(
            model_name='datafile',
            name='time_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='static/data/'),
        ),
    ]
